# Write your MySQL query statement below

SELECT CUSTOMER_NUMBER FROM ORDERS 
GROUP BY CUSTOMER_NUMBER 
HAVING COUNT(CUSTOMER_NUMBER)=(SELECT MAX(CNT) FROM
(SELECT COUNT(CUSTOMER_NUMBER) AS CNT 
FROM ORDERS
GROUP BY CUSTOMER_NUMBER) AS C);
