# Write your MySQL query statement below


SELECT CUSTOMER_ID ,COUNT(CUSTOMER_ID) AS COUNT_NO_TRANS FROM VISITS
WHERE VISIT_ID<>ALL(SELECT VISITS.VISIT_ID FROM VISITS,TRANSACTIONS
WHERE VISITS.VISIT_ID=TRANSACTIONS.VISIT_ID
GROUP BY TRANSACTIONS.VISIT_ID)
GROUP BY CUSTOMER_ID;