# Write your MySQL query statement below



SELECT S.STUDENT_ID,S.STUDENT_NAME,
U.SUBJECT_NAME,COUNT(E.SUBJECT_NAME) AS ATTENDED_EXAMS
FROM STUDENTS AS S 
CROSS JOIN SUBJECTS AS U
LEFT JOIN EXAMINATIONS AS E
ON 
E.STUDENT_ID=S.STUDENT_ID AND
E.SUBJECT_NAME=U.SUBJECT_NAME 
GROUP BY S.STUDENT_ID,U.SUBJECT_NAME,S.STUDENT_NAME
ORDER BY S.STUDENT_ID,U.SUBJECT_NAME;









